### ISSUE TITLE
Changeset version hangs when running on azure pipelines

### ISSUE THREAD

**Issue by KiriLucas** [changesets/changesets#1211]
Hey, not sure how to describe this because, since it's in a private repository, I cannot share the the whole repository, but I'll try to be as clear as possible. Basically, whenever I try running `changeset version` or `npx changeset version` or `yarn run cs:version`, my pipeline keeps hanging for a whole hour (until it reaches it's timeout).

I tested it with a simple pipeline, like this:
```yml
name: $(Build.BuildId)

jobs:
- job: release_bump
  displayName: 'Bump release'
  steps:
  - checkout: self
    persistCredentials: 'true'

  - template: /shared/tasks/npm_authenticate.yml@pipelines

  - task: NodeTool@0
    inputs:
      versionSpec: '16.20.0'
    displayName: '[PREPARE] Install NodeJS'

  - script: yarn --frozen-lockfile
    displayName: '[PREPARE] Install dependencies'

  - bash: |
          git status
          echo "Up until here, everything is ok"
          yarn run cs:version
          echo "Bash is not reaching this part"
    displayName: "[PUBLISH] Update library version"
```

`yarn run cs:version` is my package's script to `changeset version`, but I tried even with `npx changeset version` and every single time, my pipeline keeps spinning, but not logs are shown.
Worth mentioning that doing it locally works just fine, it's ONLY inside my pipeline.

I spent too many hours on this, so I might be forgetting to mention something, but any help or enlightment would be appreciated.

**Comment by dannyb648** [comment]
Having the exact same issue on our Azure pipeline. Currently found that if there is no changeset, the version command will complete, but the second we want to execute any changesets properly, it just hangs.

```
- script: |
    echo "Executing Changeset"
    pnpm changeset version
    git diff
  displayName: 'Executing Changeset'
```

**Comment by dannyb648** [comment]
Done a bit of a deep dive, wondering if the issue is around how changesets interacts with git? 

changeset version runs a git add wrapper, which looks like this

![image](https://github.com/changesets/changesets/assets/6515044/36aa3a42-a958-486a-8565-143800143f00)

I wonder if the process spawndammit use just isnt supported by Azure Pipelines? Or theres a permission needed?

**Comment by KiriLucas** [comment]
> I wonder if the process spawndammit use just isnt supported by Azure Pipelines?

I don't think so... As far as my tests went, it has an unstable behaviour as I was able to make it work on a feature branch, but then I wouldn't be able to automate my pipeline.

> Or theres a permission needed?
This could be the issue, but it's still doesn't make much sense and I couldn't find anything related to higher permissions. 😢

**Comment by dannyb648** [comment]
So to confirm, you are seeing `changeset version` actually work on a pipeline, and it is able to change the git status? (i.e. add unstaged files etc)?

**Comment by KiriLucas** [comment]
Hey, sorry for the delay!

> So to confirm, you are seeing changeset version actually work on a pipeline, and it is able to change the git status? (i.e. add unstaged files etc)?

Yes, but I stumbled upon a 403 exception... Haven't got the time to investigate further yet.

> Still hangs on my pipeline - so does feel like its specific to this function

Sorry, I also forgot to mention I tried doing that as well...
I'm seriously considering changing from changesets to something else... It shouldn't be that hard to make it work on Azure :/

**Comment by TGA88** [comment]
I solve this problem by  adding 
```          
         - checkout: self
              fetchDepth: 0
              persistCredentials: true
              clean: true

         - bash: |
              git fetch          
              git switch main

          - bash: |
              pnpm changeset status --since=main 
              pnpm changeset version

**Comment by KiriLucas** [comment]
> I solve this problem by adding
> 
> ```
>          - checkout: self
>               fetchDepth: 0
>               persistCredentials: true
>               clean: true
> 
>          - bash: |
>               git fetch          
>               git switch main
> 
>           - bash: |
>               pnpm changeset status --since=main 
>               pnpm changeset version
> ```

I'll try it, but... Any idea why that works?

**Comment by pmairoldi** [comment]
I've run into this same issue and it seems that for azure pipelines the [default checkout is shallow now](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-checkout?view=azure-pipelines#shallow-fetch). I don't know too much of how this tool works internally but I assume it needs to know about the `main` branch to be able to work properly. 

If you set the `fetchDepth` to `0` in your checkout step it disables the shallow fetch and the tool seems to work.
```yaml
- checkout: self
  fetchDepth: 0
```

**Comment by brense** [comment]
I had to explicitly fetch the target branch of the PR to get this to work in azure pipelines:
```yaml
- bash: |
    git fetch origin $TARGET_BRANCH:$TARGET_BRANCH
    npx changeset status --since $TARGET_BRANCH
  displayName: 'Check for changesets'
  condition: eq(variables['Build.Reason'], 'PullRequest')
  env:
    TARGET_BRANCH: $(System.PullRequest.TargetBranchName)
```

**Comment by Andarist** [comment]
Based on @brense and @goastler's comments I'll close this as resolved but I'd appreciate if somebody familiar with azure pipelines would prepare a documentation PR with a note about this.

**Comment by ryanwilsonperkin** [comment]
Also seeing this happen on GitHub Actions where we have a checkout of a repository with a depth of 1, necessary because of the significant size of the repository. Seems that there is still an issue with the version of `changeset version` causing it to hang indefinitely in this case

**Comment by ryanwilsonperkin** [comment]
The issue appears to stem from `@changesets/git` attempting to run `git fetch --deepen=50`, which hangs indefinitely in sufficiently large repositories and breaks the ability to rely on a shallow clone

https://github.com/changesets/changesets/blob/b57c77f8648daa11357547dda8bb85643049cc63/packages/git/src/index.ts#L125C13-L125C26
